const AVOGADRO = 6.022e23;
const MOLAR_VOLUME = 22.4;
const atomicMasses = { H: 1.008, He: 4.0026, Li: 6.94, Be: 9.0122, B: 10.81, C: 12.011, N: 14.007, O: 15.999, F: 18.998, Ne: 20.18, Na: 22.99, Mg: 24.305, Al: 26.982, Si: 28.085, P: 30.974, S: 32.06, Cl: 35.45, Ar: 39.948, K: 39.098, Ca: 40.078, Sc: 44.956, Ti: 47.867, V: 50.942, Cr: 51.996, Mn: 54.938, Fe: 55.845, Co: 58.933, Ni: 58.693, Cu: 63.546, Zn: 65.38, Ga: 69.723, Ge: 72.63, As: 74.922, Se: 78.971, Br: 79.904, Kr: 83.798, Rb: 85.468, Sr: 87.62, Y: 88.906, Zr: 91.224, Nb: 92.906, Mo: 95.95, Tc: 98, Ru: 101.07, Rh: 102.91, Pd: 106.42, Ag: 107.87, Cd: 112.41, In: 114.82, Sn: 118.71, Sb: 121.76, Te: 127.6, I: 126.9, Xe: 131.29, Cs: 132.91, Ba: 137.33, La: 138.91, Ce: 140.12, Pr: 140.91, Nd: 144.24, Pm: 145, Sm: 150.36, Eu: 151.96, Gd: 157.25, Tb: 158.93, Dy: 162.5, Ho: 164.93, Er: 167.26, Tm: 168.93, Yb: 173.05, Lu: 174.97, Hf: 178.49, Ta: 180.95, W: 183.84, Re: 186.21, Os: 190.23, Ir: 192.22, Pt: 195.08, Au: 196.97, Hg: 200.59, Tl: 204.38, Pb: 207.2, Bi: 208.98, Po: 209, At: 210, Rn: 222, Fr: 223, Ra: 226, Ac: 227, Th: 232.04, Pa: 231.04, U: 238.03, Np: 237, Pu: 244, Am: 243, Cm: 247, Bk: 247, Cf: 251, Es: 252, Fm: 257, Md: 258, No: 259, Lr: 262, Rf: 267, Db: 270, Sg: 271, Bh: 270, Hs: 277, Mt: 278, Ds: 281, Rg: 282, Cn: 285, Nh: 286, Fl: 289, Mc: 290, Lv: 293, Ts: 294, Og: 294 };
const $ = (selector) => document.querySelector(selector);
const givenValue = $("#given-value");
const givenUnit = $("#given-unit");
const wantedUnit = $("#wanted-unit");
const formulaInput = $("#formula");
const resultValue = $("#result-value");
const equation = $("#equation");
const errorMessage = $("#error-message");
let history = JSON.parse(localStorage.getItem("mole-lab-history") || "[]");
let currentMode = "convert";

function formatNumber(value) { if (value === 0) return "0"; if (Math.abs(value) >= 1e6 || Math.abs(value) < 0.001) return value.toExponential(4).replace("e+", "e"); return value.toLocaleString(undefined, { maximumFractionDigits: 4 }); }
function parseFormula(formula) {
  const tokens = formula.match(/[A-Z][a-z]?|\d+|[()]/g); if (!tokens || tokens.join("") !== formula.replace(/\s/g, "")) throw new Error("Use a valid formula, like H2O or Ca(OH)2."); let index = 0;
  function readMultiplier() { const value = tokens[index]; if (value && /^\d+$/.test(value)) { index += 1; return Number(value); } return 1; }
  function readGroup() { const counts = {}; while (index < tokens.length && tokens[index] !== ")") { if (tokens[index] === "(") { index += 1; const nested = readGroup(); if (tokens[index] !== ")") throw new Error("Check your parentheses."); index += 1; const multiplier = readMultiplier(); Object.entries(nested).forEach(([symbol, amount]) => { counts[symbol] = (counts[symbol] || 0) + amount * multiplier; }); } else { const symbol = tokens[index]; if (!(symbol in atomicMasses)) throw new Error(`"${symbol}" is not an element symbol.`); index += 1; counts[symbol] = (counts[symbol] || 0) + readMultiplier(); } } return counts; }
  const counts = readGroup(); if (index !== tokens.length) throw new Error("Check your parentheses."); return counts;
}
function getFormulaText() { return typeof formulaInput.getValue === "function" ? formulaInput.getValue("ascii-math").replace(/\s+/g, "").replace(/[_^{}]/g, "") : formulaInput.value.trim(); }
function getMolarMass() { const counts = parseFormula(getFormulaText()); return Object.entries(counts).reduce((total, [symbol, amount]) => total + atomicMasses[symbol] * amount, 0); }
function convert(value, from, to, mass) { const moles = from === "moles" ? value : from === "grams" ? value / mass : from === "molecules" ? value / AVOGADRO : value / MOLAR_VOLUME; return to === "moles" ? moles : to === "grams" ? moles * mass : to === "molecules" ? moles * AVOGADRO : moles * MOLAR_VOLUME; }
function calculate(event, saveToHistory = false) { if (event) event.preventDefault(); errorMessage.textContent = ""; try { if (currentMode === "mass") { formulaInput.setValue([...document.querySelectorAll("#element-rows .element-row")].map((row) => `${row.querySelector(".element-symbol").value}${row.querySelector(".element-count").value}`).join("")); } const value = Number(givenValue.value); if (!Number.isFinite(value) || value < 0) throw new Error("Enter a non-negative amount."); const mass = getMolarMass(); const answer = convert(value, givenUnit.value, wantedUnit.value, mass); const shownAnswer = $("#round-result").checked ? Number(answer.toPrecision(4)) : answer; resultValue.innerHTML = `${formatNumber(shownAnswer)} <small>${wantedUnit.value}</small>`; $("#formula-mass").textContent = `${formatNumber(mass)} g/mol`; equation.textContent = `${formatNumber(value)} ${givenUnit.value} -> ${formatNumber(shownAnswer)} ${wantedUnit.value}`; $("#result-status").textContent = "Calculated"; if (saveToHistory) addHistory(`${formatNumber(value)} ${givenUnit.value} -> ${formatNumber(shownAnswer)} ${wantedUnit.value}`, getFormulaText(), mass); } catch (error) { errorMessage.textContent = error.message; $("#result-status").textContent = "Needs input"; } }
function addHistory(summary, formula, mass) { if (history[0]?.summary === summary) return; history = [{ summary, formula, mass }, ...history].slice(0, 3); localStorage.setItem("mole-lab-history", JSON.stringify(history)); renderHistory(); }
function renderHistory() { $("#history-list").innerHTML = history.length ? history.map((item, index) => `<div class="history-item"><span class="history-index">0${index + 1}</span><div><strong>${item.summary}</strong><span>${item.formula} | ${formatNumber(item.mass)} g/mol</span></div><button type="button" class="history-use" data-formula="${item.formula}">Use formula</button></div>`).join("") : '<div class="empty-history">Your calculation trail will appear here.</div>'; }
function updateMode(mode) { currentMode = mode; const isMass = mode === "mass"; $("#mode-title").textContent = isMass ? "Build a molar mass" : "Convert an amount"; $("#mode-description").textContent = isMass ? "Assemble a compound and see each element's contribution." : "Choose what you know and what you need to find."; $("#formula-field").hidden = isMass; $("#mass-builder").hidden = !isMass; document.querySelectorAll(".mode-tab").forEach((tab) => tab.classList.toggle("is-active", tab.dataset.mode === mode)); if (isMass) buildElementRows(); }
function buildElementRows() { $("#element-rows").innerHTML = ["C", "H", "O"].map((symbol, index) => `<div class="element-row"><input class="element-symbol" value="${symbol}" maxlength="2" aria-label="Element ${index + 1} symbol"><input class="element-count" type="number" min="1" value="${index === 0 ? 1 : index === 1 ? 4 : 1}" aria-label="Atoms of element ${index + 1}"></div>`).join(""); }
document.querySelectorAll(".mode-tab").forEach((tab) => tab.addEventListener("click", () => updateMode(tab.dataset.mode)));
$("#calculator-form").addEventListener("submit", (event) => calculate(event, true));
[givenValue, givenUnit, wantedUnit, formulaInput, $("#round-result")].forEach((control) => control.addEventListener("input", () => calculate()));
$("#element-rows").addEventListener("input", () => calculate());
$("#add-element").addEventListener("click", () => $("#element-rows").insertAdjacentHTML("beforeend", '<div class="element-row"><input class="element-symbol" maxlength="2" placeholder="Symbol" aria-label="Element symbol"><input class="element-count" type="number" min="1" value="1" aria-label="Atoms"></div>'));
$("#clear-history").addEventListener("click", () => { history = []; localStorage.removeItem("mole-lab-history"); renderHistory(); });
$("#history-list").addEventListener("click", (event) => { const button = event.target.closest(".history-use"); if (button) { formulaInput.setValue(button.dataset.formula); updateMode("convert"); calculate(); } });
renderHistory();
calculate();
